### PR TITLE
Build libs-gui on Windows

### PR DESCRIPTION
**Pull request by qmfrederik**
This commit adds basic support for building libs-gui on Windows.

### CODE REVIEW

**Comment by triplef** [comment]
Very cool, thanks! Can you give some more info what works / is still missing here for libs-gui when you say "basic support"?

FYI @gcasa has also been working on libs-gui support on [this branch](https://github.com/gnustep/tools-windows-msvc/tree/keysight-msvc-staging).

**Comment by qmfrederik** [comment]
By "basic" I mean that some features are left out (notably printing, color pickers and models), they are removed here: https://github.com/gnustep/tools-windows-msvc/pull/26/files#diff-72fee75cf40ed99d72377c42619dafee23a15de39066840ed2a5af931606d3fb

There are a couple of compiler errors when building those areas, I'm sure we can work around those, but this felt like a quick win worth merging independently. I'd prefer tackling this with smaller PRs if that's OK with you.

Once this gets merged, I'd probably follow up with either backend or apps-systempreferences.

**Comment by triplef** [comment]
Thanks, that makes sense.

The only thing that I’d like to see before merging this is some way to say that you do/don’t want libs-gui and its dependencies. For our own purposes we have no use for it, and I imagine others who just want to use Objective-C on the command line / in libraries etc. might not need it as well and might like the extra build time/DLLs. Could we maybe add a flag `--only-base`, start the added phases at 50, and stop below 50 if the flag is set? Something along those lines would be great.

**Comment by qmfrederik** [comment]
Thanks @triplef, that makes sense. I've added a `--no-gui` flag (since we already have `--no-clean` and `--no-update`), but could rename it to `--only-base` if you prefer.

**Comment by triplef** [comment]
Thanks @qmfrederik!

**Pull request merged**
