### PR TITLE
Add libcurl build phase

### PR DESCRIPTION
**Pull request by hmelder**
There are still some patches required to the libs-base  autoconf script to get the right version from pkg-config.

### CODE REVIEW

**Comment by hmelder** [comment]
https://github.com/gnustep/libs-base/pull/269

**Comment by triplef** [comment]
Hi @hmelder, thanks for setting this up. After battling GitHub rate limit errors this is finally building on CI and seems to work ok.

I ran the tests locally and unfortunately there’s errors from [these tests](https://github.com/gnustep/libs-base/blob/47b6e9d052498c386cd20aa33059bc998181eacd/Tests/base/NSURLSession/test01.m#L125-L127) that we would probably still need to fix before merging this:

```
Running base/NSURLSession/test01.m...
Start set:       test01.m:79 ... NSURLSession test01
*   Trying 127.0.0.1:12345...
*   Trying [::1]:12345...
* Closing connection 0
Failed test:     (2022-12-22 14:42:41.072 +0100)   test01.m:125 ... request completed
Failed test:     (2022-12-22 14:42:41.072 +0100)   test01.m:127 ... unable to connect to host
2022-12-22 14:42:41.072 test01[15060:10120] Error (null)
End set:         test01.m:130 ... NSURLSession test01
Completed file:  test01.m
```

**Comment by hmelder** [comment]
> Hi @hmelder, thanks for setting this up. After battling GitHub rate limit errors this is finally building on CI and seems to work ok.
> 
> I ran the tests locally and unfortunately there’s errors from [these tests](https://github.com/gnustep/libs-base/blob/47b6e9d052498c386cd20aa33059bc998181eacd/Tests/base/NSURLSession/test01.m#L125-L127) that we would probably still need to fix before merging this:
> 
> ```
> Running base/NSURLSession/test01.m...
> Start set:       test01.m:79 ... NSURLSession test01
> *   Trying 127.0.0.1:12345...
> *   Trying [::1]:12345...
> * Closing connection 0
> Failed test:     (2022-12-22 14:42:41.072 +0100)   test01.m:125 ... request completed
> Failed test:     (2022-12-22 14:42:41.072 +0100)   test01.m:127 ... unable to connect to host
> 2022-12-22 14:42:41.072 test01[15060:10120] Error (null)
> End set:         test01.m:130 ... NSURLSession test01
> Completed file:  test01.m
> ```

Nice! I’ve seen the new commits. I’ll take a look at the errors in the unit tests, but it is probably related to the local web server.

**Comment by triplef** [comment]
That’d be fantastic, thanks. This test doesn’t have a local webserver, but instead tries to check if a connection to an nonexistent host fails correctly. I’m guessing it’s something with the libcurl integration.

**Comment by hmelder** [comment]
> That’d be fantastic, thanks. This test doesn’t have a local webserver, but instead tries to check if a connection to an nonexistent host fails correctly. I’m guessing it’s something with the libcurl integration.

That's correct. Internally GNUstep uses a curl multi handle that manages multiple easy handles. The handles itself are wrapped into objects, and there are a couple of quite complex handlers (Translating C-based callback functions into the proper NSURLSessionProtocol methods).

It would be great to have a CI log of the test. I guess I can just create a new branch in libs-base and modify the CI config?

**Comment by triplef** [comment]
> I guess I can just create a new branch in libs-base and modify the CI config?

Yes, that’d be great! Thank you.

**Comment by triplef** [comment]
I [updated](https://github.com/gnustep/libs-base/pull/285) libs-base to fix unreliable CI runs, and in the process added an option to easily specify a branch from this repo to use. Here’s a run I did with this libcurl branch:
https://github.com/gnustep/libs-base/actions/runs/3834875221/jobs/6527653656

**Comment by hmelder** [comment]
I am just setting up a new x86 VM on a root server, but compilation of libdispatch fails:

I guess this is a problem in libdispatch upstream, as we are pulling the master branch.

image

**Comment by triplef** [comment]
Which Visual Studio version are you running? I'm guessing it's most likely related to that, as there haven't been any upstream changes in libdispatch in a while.

You'll ideally want to use VS
2019, as Clang in 2022 has a number of issues with ObjC.

**Comment by hmelder** [comment]
> You'll ideally want to use VS 2019, as Clang in 2022 has a number of issues with ObjC.

I am using VS 2022 with Windows Kit 11 and Clang 15.
I'll try it with VS 2019 and Clang 16 then.

**Comment by hmelder** [comment]
MSVC supports atomic<> from version 2012 onwards (https://learn.microsoft.com/en-us/cpp/standard-library/atomic-enums?view=msvc-140). Weird.

**Comment by hmelder** [comment]
> I am using VS 2022 with Windows Kit 11 and Clang 15. I'll try it with VS 2019 and Clang 16 then.

Works with Clang 14

**Comment by hmelder** [comment]
There is a minor difference between curl error handling on Windows and UNIX which results in different results when parsing them internal in urlErrorCodeWithEasyCode (https://github.com/gnustep/libs-base/blob/efccdb1d71166cfe096f309a97747175f46c1435/Source/GSEasyHandle.m#L271). I get -1001 (NSURLErrorTimedOut) on Windows and -1004 (NSURLErrorCannotConnectToHost) on Linux.

urlErrorCodeWithEasyCode uses the curl error and a system specific error code to determine the corresponding Foundation Error Code [CURLINFO_OS_ERRNO](https://curl.se/libcurl/c/CURLINFO_OS_ERRNO.html).

I'll look into this tomorrow.

image
image

**Comment by triplef** [comment]
For some reason I actually don’t get any callback from curl when running the test locally, so the test’s run loop just times out...

I’ll try to look into it further since I’m working on various NSURLSession improvements.

**Comment by triplef** [comment]
Unfortunately I didn’t manage to track down the NSURLSession/test01 failure, so for now I marked it as hopeful as part of my NSURLSession improvements PR https://github.com/gnustep/libs-base/pull/286.

With that the libs-base CI passes:
https://github.com/gnustep/libs-base/actions/runs/4225184793

**Pull request merged**
